### PR TITLE
Add better error reporting

### PR DESCRIPTION
**Pull request by HPate-Riptide**
Probably not the right way to handle this, but it does give most useful error messages:

Before:

```

$ gulp toJSON
[21:07:57] Using gulpfile ~/myproj/gulpfile.js
[21:07:57] Starting 'toJSON'...
[21:07:57] gulp-notify: [Gulp Error] Error: Unexpected token :
[21:07:57] gulp-notify: [Gulp Error] Error: write after end
[21:07:57] Finished 'toJSON' after 460 ms
```

After:

```
$ gulp toJSON
[21:04:36] Using gulpfile ~/myproj/gulpfile.js
[21:04:36] Starting 'toJSON'...
/myproj/file/.js:3
  elements: {
          ^

SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at DestroyableTransform._transform (/Users/henry/git/elements/gulp-js-to-json/index.js:12:21)
    at DestroyableTransform.Transform._read (/Users/henry/git/elements/gulp-js-to-json/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Readable.read (/Users/henry/git/elements/gulp-js-to-json/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:362:10)
```

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/RiptideElements/gulp-js-to-json/pull/10" target="_blank">ReviewNinja

**Comment by TylerDixon** [comment]
Try this instead:
`this.emit('error', new gutil.PluginError('gulp-js-to-json', err, {showStack: true}));` 
That way we don't potentially exit amidst a series of tasks.

**Comment by DavidTPate** [comment]
@HPate-Riptide See Tyler's comment.

**Comment by TylerDixon** [comment]
Closing, as this was fixed with #18

**Pull request closed without merging**
